import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "output" / "result.csv"


def nearest(arr: np.ndarray, value: float) -> tuple[int, float]:
    idx = int(np.argmin(np.abs(arr - value)))
    return idx, float(arr[idx])


def build_plane(raw: np.ndarray, axis: str, index: int) -> tuple[np.ndarray, list[float], str, str, str]:
    xs = raw[:, 0]
    ys = raw[:, 1]
    zs = raw[:, 2]
    temps = raw[:, 3]

    ux = np.unique(xs)
    uy = np.unique(ys)
    uz = np.unique(zs)

    x_id = {v: i for i, v in enumerate(ux)}
    y_id = {v: i for i, v in enumerate(uy)}
    z_id = {v: i for i, v in enumerate(uz)}

    if axis == "z":
        plane = np.zeros((uy.size, ux.size))
        target = uz[index]
        mask = np.isclose(zs, target)
        for x, y, t in zip(xs[mask], ys[mask], temps[mask]):
            plane[y_id[y], x_id[x]] = t
        extent = [ux.min(), ux.max(), uy.min(), uy.max()]
        xlabel, ylabel = "x (m)", "y (m)"
        title = f"Temperature Cut-plane at z={target:.6f} m"
    elif axis == "y":
        plane = np.zeros((uz.size, ux.size))
        target = uy[index]
        mask = np.isclose(ys, target)
        for x, z, t in zip(xs[mask], zs[mask], temps[mask]):
            plane[z_id[z], x_id[x]] = t
        extent = [ux.min(), ux.max(), uz.min(), uz.max()]
        xlabel, ylabel = "x (m)", "z (m)"
        title = f"Temperature Cut-plane at y={target:.6f} m"
    else:  # axis == "x"
        plane = np.zeros((uy.size, uz.size))
        target = ux[index]
        mask = np.isclose(xs, target)
        for y, z, t in zip(ys[mask], zs[mask], temps[mask]):
            plane[y_id[y], z_id[z]] = t
        extent = [uz.min(), uz.max(), uy.min(), uy.max()]
        xlabel, ylabel = "z (m)", "y (m)"
        title = f"Temperature Cut-plane at x={target:.6f} m"

    return plane, extent, xlabel, ylabel, title


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot a heatmap from output/result.csv generated by `make run`.")
    parser.add_argument("--axis", choices=("x", "y", "z"), default="z", help="Cut-plane axis")
    parser.add_argument("--position", type=float, help="Physical position in meters")
    parser.add_argument("--index", type=int, help="Explicit slice index (overrides position)")
    parser.add_argument("--output", type=Path, default=ROOT / "output" / "heatmap_from_make.png", help="Save path for the heatmap")
    args = parser.parse_args()

    if not CSV_PATH.exists():
        raise FileNotFoundError(
            f"{CSV_PATH} not found. Run `make run` or `python examples/example_basic.py` first."
        )

    raw = np.loadtxt(CSV_PATH, delimiter=",", skiprows=1)
    axis = args.axis.lower()

    coords = {
        "x": np.unique(raw[:, 0]),
        "y": np.unique(raw[:, 1]),
        "z": np.unique(raw[:, 2]),
    }

    if args.index is not None:
        idx = args.index
    elif args.position is not None:
        idx, snapped = nearest(coords[axis], args.position)
        print(f"[INFO] Requested {axis}={args.position} m, using nearest grid at {snapped} m (index={idx}).")
    else:
        idx = coords[axis].size // 2
        print(f"[INFO] No position/index provided. Using {axis}-axis center slice (index={idx}).")

    if not 0 <= idx < coords[axis].size:
        raise IndexError(f"Index {idx} is out of range for axis '{axis}' (size={coords[axis].size}).")

    plane, extent, xlabel, ylabel, title = build_plane(raw, axis, idx)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    plt.figure(figsize=(7, 6))
    plt.imshow(plane, origin="lower", extent=extent, aspect="auto", cmap="inferno")
    plt.colorbar(label="Temperature (°C)")
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.tight_layout()
    plt.savefig(args.output, dpi=200)
    plt.close()
    print(f"[INFO] Heatmap saved to {args.output}")


if __name__ == "__main__":
    main()
